# Generated by Django 3.0.3 on 2020-02-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('ddate', models.DateField(default=django.utils.timezone.now)),
                ('intime', models.TimeField(default=django.utils.timezone.now)),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('sumtime', models.IntegerField(max_length=20)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
