# Generated by Django 3.0.3 on 2020-02-14 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sumtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
