# Generated by Django 3.0.3 on 2020-02-14 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200214_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sumtime',
            field=models.CharField(max_length=200),
        ),
    ]
