# Generated by Django 3.0.3 on 2020-02-14 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200214_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='outtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
