# Generated by Django 3.0.3 on 2020-02-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200216_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='garanty',
            name='name_of_model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
